### ISSUE TITLE
logstasher should not require delayed_job

### ISSUE THREAD

**Issue by alexdean** [shadabahmed/logstasher#85]
d2a80e452c599670726e47de5501e4e86d9b4597 makes DelayedJob a runtime dependency for Logstasher. could this please be made optional? Logstasher should not require installation of DelayedJob.

cc @MarcGrimme

**Comment by Sija** [comment]
:+1:

**Comment by MarcGrimme** [comment]
I agree. Somehow I had this in mind but could not make it happen. Mainly the problem is the I guess in the (logstasher.gemspec)[https://github.com/shadabahmed/logstasher/commit/d2a80e452c599670726e47de5501e4e86d9b4597#diff-383d06d8b54a0a7bf576f731f82630e2R15]. The only reasonable solution could be to make a second gem like ``logstasher-delayed`` job out of it.
I'll try to see what I can do.

**Comment by Sija** [comment]
@MarcGrimme you can simply omit it from `.gemspec` and check it only on the runtime.

**Comment by MarcGrimme** [comment]
Should be fixed [here](https://github.com/shadabahmed/logstasher/pull/88)

**Comment by Sija** [comment]
@MarcGrimme could we have a new gem version cut?

**Comment by MarcGrimme** [comment]
Bumped version to 0.8.1. Hope this is ok.

**Comment by Sija** [comment]
Looks great, thanks!
I hope it'll land in the `master` branch and on _rubygems_ soon ^^
